name: Simple Test

# Run tests on every push and pull request
on: [push, pull_request]

jobs:
  test:
    name: Run Caesar Cipher Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -v

    - name: Test passed!
      run: echo "All tests passed successfully! 🎉"